FROM golang:1.16.7-alpine

RUN apk --update --no-cache add git build-base openssh curl nmap mysql-client tzdata bash ca-certificates jq && \
  update-ca-certificates

ENV TZ Asia/Tokyo

COPY install.sh ./
RUN cat install.sh | sh -s -- -b $(go env GOPATH)/bin

WORKDIR /himo-outgame

COPY go.mod go.sum /himo-outgame/
RUN go mod download

COPY . /himo-outgame

RUN chmod 755 ./entry-point.sh
ENTRYPOINT [ "./entry-point.sh" ]
