// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// HistoryManagerClient is the client API for HistoryManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HistoryManagerClient interface {
	List(ctx context.Context, in *ListHistoryRequest, opts ...grpc.CallOption) (*ListHistoryResponse, error)
}

type historyManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoryManagerClient(cc grpc.ClientConnInterface) HistoryManagerClient {
	return &historyManagerClient{cc}
}

func (c *historyManagerClient) List(ctx context.Context, in *ListHistoryRequest, opts ...grpc.CallOption) (*ListHistoryResponse, error) {
	out := new(ListHistoryResponse)
	err := c.cc.Invoke(ctx, "/himo.v1.HistoryManager/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryManagerServer is the server API for HistoryManager service.
// All implementations must embed UnimplementedHistoryManagerServer
// for forward compatibility
type HistoryManagerServer interface {
	List(context.Context, *ListHistoryRequest) (*ListHistoryResponse, error)
	mustEmbedUnimplementedHistoryManagerServer()
}

// UnimplementedHistoryManagerServer must be embedded to have forward compatible implementations.
type UnimplementedHistoryManagerServer struct {
}

func (UnimplementedHistoryManagerServer) List(context.Context, *ListHistoryRequest) (*ListHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedHistoryManagerServer) mustEmbedUnimplementedHistoryManagerServer() {}

// UnsafeHistoryManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistoryManagerServer will
// result in compilation errors.
type UnsafeHistoryManagerServer interface {
	mustEmbedUnimplementedHistoryManagerServer()
}

func RegisterHistoryManagerServer(s grpc.ServiceRegistrar, srv HistoryManagerServer) {
	s.RegisterService(&_HistoryManager_serviceDesc, srv)
}

func _HistoryManager_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryManagerServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/himo.v1.HistoryManager/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryManagerServer).List(ctx, req.(*ListHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HistoryManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "himo.v1.HistoryManager",
	HandlerType: (*HistoryManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _HistoryManager_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/v1/himo/proto/history.proto",
}
