// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: grpc/v1/himo/proto/theme.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Theme struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sentence string `protobuf:"bytes,2,opt,name=sentence,proto3" json:"sentence,omitempty"`
}

func (x *Theme) Reset() {
	*x = Theme{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_himo_proto_theme_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Theme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Theme) ProtoMessage() {}

func (x *Theme) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_himo_proto_theme_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Theme.ProtoReflect.Descriptor instead.
func (*Theme) Descriptor() ([]byte, []int) {
	return file_grpc_v1_himo_proto_theme_proto_rawDescGZIP(), []int{0}
}

func (x *Theme) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Theme) GetSentence() string {
	if x != nil {
		return x.Sentence
	}
	return ""
}

type ThemeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sentence string `protobuf:"bytes,1,opt,name=sentence,proto3" json:"sentence,omitempty"`
}

func (x *ThemeRequest) Reset() {
	*x = ThemeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_himo_proto_theme_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThemeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThemeRequest) ProtoMessage() {}

func (x *ThemeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_himo_proto_theme_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThemeRequest.ProtoReflect.Descriptor instead.
func (*ThemeRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_himo_proto_theme_proto_rawDescGZIP(), []int{1}
}

func (x *ThemeRequest) GetSentence() string {
	if x != nil {
		return x.Sentence
	}
	return ""
}

type ThemeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Theme *Theme `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
}

func (x *ThemeResponse) Reset() {
	*x = ThemeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_himo_proto_theme_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThemeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThemeResponse) ProtoMessage() {}

func (x *ThemeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_himo_proto_theme_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThemeResponse.ProtoReflect.Descriptor instead.
func (*ThemeResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_himo_proto_theme_proto_rawDescGZIP(), []int{2}
}

func (x *ThemeResponse) GetTheme() *Theme {
	if x != nil {
		return x.Theme
	}
	return nil
}

type ListThemeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListThemeRequest) Reset() {
	*x = ListThemeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_himo_proto_theme_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListThemeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThemeRequest) ProtoMessage() {}

func (x *ListThemeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_himo_proto_theme_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThemeRequest.ProtoReflect.Descriptor instead.
func (*ListThemeRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_himo_proto_theme_proto_rawDescGZIP(), []int{3}
}

type ListThemeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Themes []*Theme `protobuf:"bytes,1,rep,name=themes,proto3" json:"themes,omitempty"`
}

func (x *ListThemeResponse) Reset() {
	*x = ListThemeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_himo_proto_theme_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListThemeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThemeResponse) ProtoMessage() {}

func (x *ListThemeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_himo_proto_theme_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThemeResponse.ProtoReflect.Descriptor instead.
func (*ListThemeResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_himo_proto_theme_proto_rawDescGZIP(), []int{4}
}

func (x *ListThemeResponse) GetThemes() []*Theme {
	if x != nil {
		return x.Themes
	}
	return nil
}

var File_grpc_v1_himo_proto_theme_proto protoreflect.FileDescriptor

var file_grpc_v1_himo_proto_theme_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x69, 0x6d, 0x6f, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x68, 0x69, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x22, 0x33, 0x0a, 0x05, 0x54, 0x68, 0x65,
	0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x2a,
	0x0a, 0x0c, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x35, 0x0a, 0x0d, 0x54, 0x68,
	0x65, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x74,
	0x68, 0x65, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x68, 0x69, 0x6d,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x05, 0x74, 0x68, 0x65, 0x6d,
	0x65, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3b, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x68, 0x65,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x74, 0x68,
	0x65, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x68, 0x69, 0x6d,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x06, 0x74, 0x68, 0x65, 0x6d,
	0x65, 0x73, 0x32, 0x8a, 0x01, 0x0a, 0x0c, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e,
	0x68, 0x69, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x68, 0x69, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x68, 0x65, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f,
	0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x68, 0x69, 0x6d, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x68, 0x69, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x54, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61,
	0x6d, 0x62, 0x6f, 0x6f, 0x6f, 0x6f, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x68, 0x69, 0x6d, 0x6f, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x69, 0x6d, 0x6f,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_v1_himo_proto_theme_proto_rawDescOnce sync.Once
	file_grpc_v1_himo_proto_theme_proto_rawDescData = file_grpc_v1_himo_proto_theme_proto_rawDesc
)

func file_grpc_v1_himo_proto_theme_proto_rawDescGZIP() []byte {
	file_grpc_v1_himo_proto_theme_proto_rawDescOnce.Do(func() {
		file_grpc_v1_himo_proto_theme_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_v1_himo_proto_theme_proto_rawDescData)
	})
	return file_grpc_v1_himo_proto_theme_proto_rawDescData
}

var file_grpc_v1_himo_proto_theme_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grpc_v1_himo_proto_theme_proto_goTypes = []interface{}{
	(*Theme)(nil),             // 0: himo.v1.Theme
	(*ThemeRequest)(nil),      // 1: himo.v1.ThemeRequest
	(*ThemeResponse)(nil),     // 2: himo.v1.ThemeResponse
	(*ListThemeRequest)(nil),  // 3: himo.v1.ListThemeRequest
	(*ListThemeResponse)(nil), // 4: himo.v1.ListThemeResponse
}
var file_grpc_v1_himo_proto_theme_proto_depIdxs = []int32{
	0, // 0: himo.v1.ThemeResponse.theme:type_name -> himo.v1.Theme
	0, // 1: himo.v1.ListThemeResponse.themes:type_name -> himo.v1.Theme
	1, // 2: himo.v1.ThemeManager.Create:input_type -> himo.v1.ThemeRequest
	3, // 3: himo.v1.ThemeManager.List:input_type -> himo.v1.ListThemeRequest
	2, // 4: himo.v1.ThemeManager.Create:output_type -> himo.v1.ThemeResponse
	4, // 5: himo.v1.ThemeManager.List:output_type -> himo.v1.ListThemeResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpc_v1_himo_proto_theme_proto_init() }
func file_grpc_v1_himo_proto_theme_proto_init() {
	if File_grpc_v1_himo_proto_theme_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_v1_himo_proto_theme_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Theme); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_himo_proto_theme_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThemeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_himo_proto_theme_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThemeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_himo_proto_theme_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListThemeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_himo_proto_theme_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListThemeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_v1_himo_proto_theme_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_v1_himo_proto_theme_proto_goTypes,
		DependencyIndexes: file_grpc_v1_himo_proto_theme_proto_depIdxs,
		MessageInfos:      file_grpc_v1_himo_proto_theme_proto_msgTypes,
	}.Build()
	File_grpc_v1_himo_proto_theme_proto = out.File
	file_grpc_v1_himo_proto_theme_proto_rawDesc = nil
	file_grpc_v1_himo_proto_theme_proto_goTypes = nil
	file_grpc_v1_himo_proto_theme_proto_depIdxs = nil
}
